### ISSUE TITLE
Please add iOS Support 

### ISSUE THREAD

**Issue by Ishu07** [wit-ai/voicesdk-unreal#19]
Please add libs for iOS releases

Open to testing and contributing

**Comment by Ishu07** [comment]
Is there Any progress?

**Comment by wangpingsx** [comment]
@Ishu07  Happy New Year!!!  

We found it is challenging to do that for UE4. But there may some hope on UE5.1.

We just supported UE5.1 for Windows before Xmas, not on Mac yet. But we will start planning soon.

It would be great to see how much demands is this, so we can change our priority accordingly. I will keep this ticket open, if people interested on this, please thumbs up on this. 
Thanks
