### ISSUE TITLE
Is there a dictation example?

### ISSUE THREAD

**Issue by unktomi** [wit-ai/voicesdk-unreal#21]
If so where can I find it? And is there some kind of getting started guide? I installed these plugins and created a wit.ai project but it is not obvious how to connect them.

**Comment by wangpingsx** [comment]
Hi @unktomi  Happy New Year!
I am so happy to know that you are using our plugin.
The Dictation feature is working, but it is not officially released yet, so the doc is not ready yet.
To connect Wit.ai with the plugin, you will need to set a config to the Experiment Actor, please check this doc for detail:  
https://developer.oculus.com/documentation/unreal/vsdk-integrate-voice

Please let me know if that help.
Thanks

**Comment by unktomi** [comment]
Peter,

Thanks for your response. That documentation doesn't seem to match what I see in UE 5.1. In 5.1, there is an Oculus menu which provides a ui that allows me to create a configuration asset. But I'm not sure what the next step after that is?

**Comment by unktomi** [comment]
Ok well I seem to have fumbled my way through. I created a voice experience actor instance and set the configuration on it. Then I created a blueprint class that extended DictationExperience and instantiated it and I was able to get dictation transcription events.

**Comment by wangpingsx** [comment]
@unktomi  glade you made it to work.     
BTW, the Oculus menu is a very new feature, we are working in progress updating the document.

**Comment by wangpingsx** [comment]
@unktomi  
Here is our dictation doc:
https://developer.oculus.com/documentation/unreal/vsdk-dictation
You can find a sample on this sample project: 
https://github.com/wit-ai/voicesdk-unreal-samples

(Note: the dictation sample is in this map:  https://github.com/wit-ai/voicesdk-unreal-samples/blob/main/Content/VoiceSDK/Demo/Levels/DictationDemo.umap)

Hope you found this is useful.

BTW, I am working on the doc to explain how to use the "oculus" menu to create config.
Thanks
