### ISSUE TITLE
Switching Levels Crashes Build

### ISSUE THREAD

**Issue by misterk99** [wit-ai/voicesdk-unreal#40]
I have been having this issue for quite some time now,
Whenever I make a build for the Oculus Quest 2, The Voice SDK works great, but as soon as I try to open another scene the app just crashes.

Without this plugin, the whole application runs fine and only when the voice SDK gets activated and then tries to open another level it crashes the application completely. Im on Unreal 5.0 and using Voice SDK version 53.0.1
Crashlog(s) provided.
[TFE-BrushTest-backup-2023.10.24-11.51.01.log](https://github.com/wit-ai/voicesdk-unreal/files/13114178/TFE-BrushTest-backup-2023.10.24-11.51.01.log)
[TFE-BrushTest.log](https://github.com/wit-ai/voicesdk-unreal/files/13114179/TFE-BrushTest.log)

**Comment by IanSlatteryMeta** [comment]
Thanks for bringing this to our attention. We have verified the issue and will have a fix for the problem in the next release.

**Comment by misterk99** [comment]
Is there any ETA on the update? This year?

**Comment by IanSlatteryMeta** [comment]
This issue should be resolved as of the 59.0.0 release
