### ISSUE TITLE
Unreal crashes on creating a config file

### ISSUE THREAD

**Issue by FoleyTim** [wit-ai/voicesdk-unreal#49]
When creating a config file, I enter server token + name and when I click create Unreal crashes. I have tried this on multiple different computers now, even with fresh projects. I am using UE 5.3 

error I get is:

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000300000070
UnrealEditor_Core!mi_free() [D:\build\++UE5\Sync\Engine\Source\ThirdParty\mimalloc\src\[alloc.c:486](http://alloc.c:486/)]
UnrealEditor_Core!FMemory::Free() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\HAL\[FMemory.inl:141](http://fmemory.inl:141/)]
UnrealEditor_HTTP!`anonymous namespace'::CurlFree() [D:\build\++UE5\Sync\Engine\Source\Runtime\Online\HTTP\Private\Curl\[CurlHttp.h:70](http://curlhttp.h:70/)]
UnrealEditor_HTTP!Curl_setstropt()
UnrealEditor_HTTP!Curl_vsetopt()
UnrealEditor_HTTP!curl_easy_setopt()
UnrealEditor_HTTP!FCurlHttpRequest::SetupRequestHttpThread() [D:\build\++UE5\Sync\Engine\Source\Runtime\Online\HTTP\Private\Curl\[CurlHttp.cpp:927](http://curlhttp.cpp:927/)]
UnrealEditor_HTTP!FCurlHttpThread::StartThreadedRequest() [D:\build\++UE5\Sync\Engine\Source\Runtime\Online\HTTP\Private\Curl\[CurlHttpThread.cpp:77](http://curlhttpthread.cpp:77/)]
UnrealEditor_HTTP!FHttpThreadBase::Process() [D:\build\++UE5\Sync\Engine\Source\Runtime\Online\HTTP\Private\[HttpThread.cpp:245](http://httpthread.cpp:245/)]
UnrealEditor_HTTP!FLegacyHttpThread::Run() [D:\build\++UE5\Sync\Engine\Source\Runtime\Online\HTTP\Private\[HttpThread.cpp:390](http://httpthread.cpp:390/)]
UnrealEditor_Core!FRunnableThreadWin::Run() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Windows\[WindowsRunnableThread.cpp:149](http://windowsrunnablethread.cpp:149/)]

**Comment by IanSlatteryMeta** [comment]
Are you using the Marketplace plugin, or the Release package from this Repo? There is a known issue with the 5.3 Marketplace plugin which requires rebuilding the plugin manually. The quickest resolution is to uninstall the Marketplace plugin and use the latest Release version from this repo
