### ISSUE TITLE
v67 changelog missing.

### ISSUE THREAD

**Issue by alefriant** [wit-ai/voicesdk-unreal#53]
Hi!
Could you submit the log for the v67 please? I wasn't able to find it. 

Hi @IanSlatteryMeta 
Has this been solved in the release 67? I wasn't able to find any changelog after the v63. 
If not, when could we expect a v68 with the fix included for the Quest platforms?

_Originally posted by @alefriant in https://github.com/wit-ai/voicesdk-unreal/issues/51#issuecomment-2335065113_

**Comment by IanSlatteryMeta** [comment]
Apologies for the missing changelog. The release summary does have the details of the changes.
